### ISSUE TITLE
`number` is not a valid PHP type

### ISSUE THREAD

**Issue by aboks** [markrogoyski/math-php#456] opened 2022-07-28 12:54 UTC
Methods like `MatrixFactory::create()` and some others make use of a type `number` in their `@param` annotations (i.e. `number[][] $A` for `MatrixFactory::create()`). However, `number` is not a valid/existing PHP type, and therefore interpreted as a classname. This causes static analysis tools like Psalm to complain when calling these methods, with errors like
```
Argument 1 of MathPHP\LinearAlgebra\MatrixFactory::create expects array<array-key, array<array-key, MathPHP\LinearAlgebra\number>>, array{array{-1, 0, 0}, array{0, -1, 0}, array{0, 0, 1}} provided
```
The correct type to use here is probably something like `int|float|Complex` (if complex numbers are allowed, like in `MatrixFactory::create()`).

**Comment by markrogoyski** [comment] 2022-07-29 02:45
Hi @aboks,

Thank you for your continued interest in improving MathPHP.

At some point in the past I remember `number` being a valid PHPDoc pseudo type, but I can't seem to find any documentation to back that up. I'll go through the library and clean up the `@param` annotations and replace `number` with more accurate union types.

Thanks for bringing this up. I'll let you know when I've updated the type annotations.

Mark

**Comment by markrogoyski** [comment] 2022-12-31 07:21
Hi @aboks,

This has been fixed in the latest version [v2.7.0](https://github.com/markrogoyski/math-php/releases/tag/v2.7.0). I've changed the `number` param annotations to more specific types. Thanks for bringing this to my attention.

If you find any other issues with incorrect types, don't hesitate to create a new issue to request fixes.

Thanks again for your interest in improving MathPHP!
Mark

**Closed by markrogoyski** 2022-12-31 07:21 UTC

**Comment by aboks** [comment] 2023-05-08 11:05
@markrogoyski I noticed that in v2.8.0 some of the the `number` parameter annotations have returned, I guess due to #465. Would it be possible to also convert these to a more specific union type that Psalm understands?

**Comment by markrogoyski** [comment] 2023-05-08 15:22
Hi @aboks,

Thanks for your continued interest in MathPHP.

Sorry about the static analysis regression. I think we can get this fixed pretty quickly. Can you open a new issue, and in that, post what version of Psalm you are using and what command/configuration you use to run it, and a sample output of the error? That will be helpful.

Also, since MathPHP now runs PHPStan fully passing in CI, it may be worth considering also adding Psalm as well. It should not be as much of a lift to get Psalm fully passing now that PHPStan is passing. I'll work on getting your immediate number issue first, but long term, adding Psalm to the CI run might be something I also look into as a followup.

Thanks,
Mark

**Comment by aboks** [comment] 2023-05-09 09:31
Hi @markrogoyski, thanks for your quick reply and being an awesome maintainer in general! I've created #470 as a followup, with a link to a GitHub project where you can easily reproduce the problem.
