### ISSUE TITLE
Started a Tensor Class

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#88] opened 2016-08-19 00:28 UTC
https://github.com/Beakerboy/math-php/blob/patch-1/src/LinearAlgebra/Tensor.php

Feel free to look it over, over suggestions or pull requests...or copy anything I have into master. It's nowhere near done, but the concepts are laid out.

**Comment by markrogoyski** [comment] 2016-08-19 07:04
Cool. I'll have to read up and familiarize myself on tensors.

**Comment by Beakerboy** [comment] 2016-08-19 13:20
I'd put it at pretty low priority. I just worked on what I have as an exercise.

**Comment by markrogoyski** [comment] 2017-03-28 15:03
Closing this as duplicate of https://github.com/markrogoyski/math-php/issues/194. The other thread has a lot of good discussion so keeping that thread.

**Closed by markrogoyski** 2017-03-28 15:03 UTC
Labels: duplicate, enhancement
