### ISSUE TITLE
Error in the Matrix Solver

### ISSUE THREAD

**Issue by Labaneseren** [markrogoyski/math-php#386] opened 2020-09-27 20:22 UTC
Dear team behind this amazing set of tools: thanks for making my life a lot easier. I am using Math PHP and loving it. 
I have encountered what I believe to be a shortcoming of the solver for matrix equations. I am using the solver succesfully for many other matrices, but for this one I am getting this error: 
![billede](https://user-images.githubusercontent.com/71987828/94374852-81474180-010f-11eb-8373-f9114e00a3d6.png)
![billede](https://user-images.githubusercontent.com/71987828/94374867-9d4ae300-010f-11eb-95ee-7f42a11b9658.png)

I know the matrix equation can be solved, since I am doing this without any problems in other math software such as Maple. 
You can have a look at the matrix structure in the attached file. Perhaps it is this structure which forces the solver to do the devision by zero? I am not adept at matrix decomposition, but maybe this is an inherent shortcoming of LU decomposition? 
Do you have any workaround? 

[matrix49x49.xlsx](https://github.com/markrogoyski/math-php/files/5289017/matrix49x49.xlsx)

**Comment by markrogoyski** [comment] 2020-09-27 23:18
Hi @Labaneseren,

Thank you for your interest in MathPHP and your kind words. I'm sorry you're having some difficulties. Let's see if we can figure out what is going on.

It sounds like you are using the `Matrix::solve` method and getting a division by zero error. I got the matrix from your Excel sheet. Can you provide the Vector/array that you are sending to the `solve` method to get this error? I'd like to reproduce exactly what you are seeing to understand what is going on. So please provide your input b Vector/array to this matrix to solve.

Thanks,
Mark

**Comment by Beakerboy** [comment] 2020-09-28 02:23
As an aside, if R is passed a single matrix to the `solve()` function, it returns the matrix inverse.

**Comment by Labaneseren** [comment] 2020-09-28 05:59
This is my b vector
[b-49.xlsx](https://github.com/markrogoyski/math-php/files/5290164/b-49.xlsx) 

And I'm using the Matrix::solve like this: 
$P = $A->solve($b);

**Comment by markrogoyski** [comment] 2020-09-28 16:13
Hi @Labaneseren,

Thank you for providing the input. I was able to reproduce the issue. I'll report back if I have any information as to why what is going on and how we might fix this.

Mark

**Comment by markrogoyski** [comment] 2020-09-28 16:20
Hi @Labaneseren,

To confirm, can you provide what you expect the resultant x to be from the solves system of linear equations?

Thanks,
Mark

**Comment by Beakerboy** [comment] 2020-09-28 17:31
It is solvable in R:
```
A = matrix(c(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.015625, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.03125, 0, 0, 0, 0, 0, 0, 0, 0, 0.59375, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.07421875, 0, 0, 0, 0, 0.583333333333333, 0.166666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0729166666666667, 0.0208333333333333, 0, 0, 0, 0, 0, 0, 0, 0.260416666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0325520833333333, 0, 0, 0, 0, 0.166666666666667, 0.666666666666667, 0.166666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0208333333333333, 0.0833333333333333, 0.0208333333333333, 0, 0, 0, 0, 0, 0, 0.0208333333333333, 0, 0, 0, 0, 0.0208333333333333, 0, 0, 0, 0, 0.00260416666666667, 0.00260416666666667, 0, 0, 0, 0, 0.166666666666667, 0.583333333333333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0208333333333333, 0.0729166666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.260416666666667, 0, 0, 0, 0, 0, 0.0325520833333333, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.03125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.59375, 0, 0, 0, 0, 0, 0.07421875, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.125, 0, 0, 0, 0, 0, 0.015625, 0, 0, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.59375, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.03125, 0, 0, 0, 0, 0, 0, 0, 0, 0.07421875, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0625, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1484375, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1484375, 0, 0, 0, 0, 0, 0, 0, 0, 0.3525390625, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.145833333333333, 0.0416666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.346354166666667, 0.0989583333333333, 0, 0, 0, 0, 0, 0, 0, 0, 0.0651041666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0.154622395833333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0416666666666667, 0.166666666666667, 0.0416666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0989583333333333, 0.395833333333333, 0.0989583333333333, 0, 0, 0, 0, 0, 0, 0, 0.00520833333333333, 0, 0, 0, 0, 0.00520833333333333, 0, 0, 0, 0.0123697916666667, 0.0123697916666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0416666666666667, 0.145833333333333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0989583333333333, 0.346354166666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0651041666666667, 0, 0, 0, 0, 0.154622395833333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0625, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1484375, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1484375, 0, 0, 0, 0, 0.3525390625, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.59375, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.03125, 0, 0, 0, 0, 0.07421875, 0, 0, 0, 0, 0, 0, 0, 0.583333333333333, 0, 0, 0, 0, 0.166666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.260416666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0729166666666667, 0.0208333333333333, 0, 0, 0, 0, 0, 0, 0, 0.0325520833333333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.145833333333333, 0, 0, 0, 0, 0.0416666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0651041666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.346354166666667, 0.0989583333333333, 0, 0, 0, 0, 0, 0, 0, 0.154622395833333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.340277777777778, 0.0972222222222222, 0, 0, 0, 0.0972222222222222, 0.0277777777777778, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.151909722222222, 0.0434027777777778, 0, 0, 0, 0, 0, 0, 0, 0, 0.151909722222222, 0.0434027777777778, 0, 0, 0, 0, 0, 0, 0, 0.0678168402777778, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0972222222222222, 0.388888888888889, 0.0972222222222222, 0, 0, 0.0277777777777778, 0.111111111111111, 0.0277777777777778, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0434027777777778, 0.173611111111111, 0.0434027777777778, 0, 0, 0, 0, 0, 0, 0, 0.0121527777777778, 0.00347222222222222, 0, 0, 0, 0.0121527777777778, 0.00347222222222222, 0, 0, 0.00542534722222222, 0.00542534722222222, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0972222222222222, 0.340277777777778, 0, 0, 0, 0.0277777777777778, 0.0972222222222222, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0434027777777778, 0.151909722222222, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.151909722222222, 0.0434027777777778, 0, 0, 0, 0.0678168402777778, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.145833333333333, 0, 0, 0, 0, 0.0416666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0651041666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.346354166666667, 0.0989583333333333, 0, 0, 0, 0.154622395833333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.583333333333333, 0, 0, 0, 0, 0.166666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.260416666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0729166666666667, 0.0208333333333333, 0, 0, 0, 0.0325520833333333, 0, 0, 0, 0, 0, 0, 0, 0.166666666666667, 0, 0, 0, 0, 0.666666666666667, 0, 0, 0, 0, 0.166666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0208333333333333, 0, 0, 0, 0, 0.0208333333333333, 0, 0, 0, 0, 0, 0.0208333333333333, 0.0833333333333333, 0.0208333333333333, 0, 0, 0, 0, 0, 0, 0.00260416666666667, 0, 0.00260416666666667, 0, 0, 0, 0, 0, 0, 0, 0.0416666666666667, 0, 0, 0, 0, 0.166666666666667, 0, 0, 0, 0, 0.0416666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.00520833333333333, 0, 0, 0, 0, 0.00520833333333333, 0, 0, 0, 0, 0.0989583333333333, 0.395833333333333, 0.0989583333333333, 0, 0, 0, 0, 0, 0, 0.0123697916666667, 0, 0.0123697916666667, 0, 0, 0, 0, 0, 0, 0, 0.0972222222222222, 0.0277777777777778, 0, 0, 0, 0.388888888888889, 0.111111111111111, 0, 0, 0, 0.0972222222222222, 0.0277777777777778, 0, 0, 0, 0, 0, 0, 0, 0, 0.0121527777777778, 0.00347222222222222, 0, 0, 0, 0.0121527777777778, 0.00347222222222222, 0, 0, 0, 0.0434027777777778, 0.173611111111111, 0.0434027777777778, 0, 0, 0, 0, 0, 0, 0.00542534722222222, 0, 0.00542534722222222, 0, 0, 0, 0, 0, 0, 0, 0.0277777777777778, 0.111111111111111, 0.0277777777777778, 0, 0, 0.111111111111111, 0.444444444444444, 0.111111111111111, 0, 0, 0.0277777777777778, 0.111111111111111, 0.0277777777777778, 0, 0, 0, 0, 0, 0, 0, 0.00347222222222222, 0.0138888888888889, 0.00347222222222222, 0, 0, 0.00347222222222222, 0.0138888888888889, 0.00347222222222222, 0, 0, 0.00347222222222222, 0.0138888888888889, 0.00347222222222222, 0, 0, 0.00347222222222222, 0.0138888888888889, 0.00347222222222222, 0, 0.000434027777777778, 0.000434027777777778, 0.000434027777777778, 0.000434027777777778, 0, 0, 0, 0, 0, 0, 0, 0.0277777777777778, 0.0972222222222222, 0, 0, 0, 0.111111111111111, 0.388888888888889, 0, 0, 0, 0.0277777777777778, 0.0972222222222222, 0, 0, 0, 0, 0, 0, 0, 0, 0.00347222222222222, 0.0121527777777778, 0, 0, 0, 0.00347222222222222, 0.0121527777777778, 0, 0, 0, 0, 0, 0, 0, 0.0434027777777778, 0.173611111111111, 0.0434027777777778, 0, 0, 0.00542534722222222, 0, 0.00542534722222222, 0, 0, 0, 0, 0, 0, 0, 0, 0.0416666666666667, 0, 0, 0, 0, 0.166666666666667, 0, 0, 0, 0, 0.0416666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.00520833333333333, 0, 0, 0, 0, 0.00520833333333333, 0, 0, 0, 0, 0, 0, 0, 0.0989583333333333, 0.395833333333333, 0.0989583333333333, 0, 0, 0.0123697916666667, 0, 0.0123697916666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.166666666666667, 0, 0, 0, 0, 0.666666666666667, 0, 0, 0, 0, 0.166666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0208333333333333, 0, 0, 0, 0, 0.0208333333333333, 0, 0, 0, 0, 0, 0, 0.0208333333333333, 0.0833333333333333, 0.0208333333333333, 0, 0, 0.00260416666666667, 0, 0.00260416666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.166666666666667, 0, 0, 0, 0, 0.583333333333333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.260416666666667, 0, 0, 0, 0, 0, 0, 0.0208333333333333, 0.0729166666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0.0325520833333333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0416666666666667, 0, 0, 0, 0, 0.145833333333333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0651041666666667, 0, 0, 0, 0, 0, 0.0989583333333333, 0.346354166666667, 0, 0, 0, 0, 0, 0, 0, 0, 0.154622395833333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0972222222222222, 0.0277777777777778, 0, 0, 0, 0.340277777777778, 0.0972222222222222, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.151909722222222, 0.0434027777777778, 0, 0, 0, 0, 0.0434027777777778, 0.151909722222222, 0, 0, 0, 0, 0, 0, 0, 0, 0.0678168402777778, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0277777777777778, 0.111111111111111, 0.0277777777777778, 0, 0, 0.0972222222222222, 0.388888888888889, 0.0972222222222222, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0434027777777778, 0.173611111111111, 0.0434027777777778, 0, 0, 0, 0.00347222222222222, 0.0121527777777778, 0, 0, 0, 0.00347222222222222, 0.0121527777777778, 0, 0, 0, 0.00542534722222222, 0.00542534722222222, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0277777777777778, 0.0972222222222222, 0, 0, 0, 0.0972222222222222, 0.340277777777778, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0434027777777778, 0.151909722222222, 0, 0, 0, 0, 0, 0, 0, 0, 0.0434027777777778, 0.151909722222222, 0, 0, 0, 0, 0.0678168402777778, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0416666666666667, 0, 0, 0, 0, 0.145833333333333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0651041666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0.0989583333333333, 0.346354166666667, 0, 0, 0, 0, 0.154622395833333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.166666666666667, 0, 0, 0, 0, 0.583333333333333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.260416666666667, 0, 0, 0, 0, 0, 0, 0, 0.0208333333333333, 0.0729166666666667, 0, 0, 0, 0, 0.0325520833333333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.59375, 0, 0, 0, 0, 0, 0, 0, 0.03125, 0, 0, 0, 0, 0, 0, 0, 0, 0.07421875, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0625, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1484375, 0, 0, 0, 0, 0, 0, 0.1484375, 0, 0, 0, 0, 0, 0, 0, 0, 0.3525390625, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.145833333333333, 0.0416666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.346354166666667, 0.0989583333333333, 0, 0, 0, 0, 0, 0.0651041666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0.154622395833333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0416666666666667, 0.166666666666667, 0.0416666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0989583333333333, 0.395833333333333, 0.0989583333333333, 0, 0, 0, 0, 0.00520833333333333, 0, 0, 0, 0, 0.00520833333333333, 0, 0, 0, 0.0123697916666667, 0.0123697916666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0416666666666667, 0.145833333333333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0989583333333333, 0.346354166666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0651041666666667, 0, 0, 0, 0, 0.154622395833333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0625, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1484375, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1484375, 0, 0, 0, 0, 0.3525390625, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.59375, 0, 0, 0, 0, 0, 0, 0, 0, 0.03125, 0, 0, 0, 0, 0.07421875, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.125, 0, 0, 0, 0, 0, 0, 0, 0, 0.125, 0, 0, 0, 0, 0, 0, 0, 0.015625, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.03125, 0, 0, 0, 0, 0, 0, 0, 0.59375, 0, 0, 0, 0, 0, 0, 0, 0.07421875, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.583333333333333, 0.166666666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0.0729166666666667, 0.0208333333333333, 0, 0, 0, 0, 0, 0, 0.260416666666667, 0, 0, 0, 0, 0, 0, 0, 0.0325520833333333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.166666666666667, 0.666666666666667, 0.166666666666667, 0, 0, 0, 0, 0, 0, 0, 0.0208333333333333, 0.0833333333333333, 0.0208333333333333, 0, 0, 0, 0, 0, 0.0208333333333333, 0, 0, 0, 0, 0.0208333333333333, 0, 0, 0.00260416666666667, 0.00260416666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.166666666666667, 0.583333333333333, 0, 0, 0, 0, 0, 0, 0, 0, 0.0208333333333333, 0.0729166666666667, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.260416666666667, 0, 0, 0, 0.0325520833333333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.03125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.59375, 0, 0, 0, 0.07421875, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.125, 0, 0, 0, 0.015625 
),nrow=49,ncol=49)

b= matrix(c(0, -0.10007440192611, -0.27923592701769, -0.50604404310114, -0.76851634089618, -0.95591916066399, -1.1171295222139, -1.3522038868894, -1.630181622005, -1.9393213323533, -1.8884943297772, -2.106903818766, -2.3921503974489, -2.7145094057125, -3.0627671927672, -2.7749515869456, -3.0452265418301, -3.3736794800877, -3.7325476042344, -4.1114188504787, -3.5936432326846, -3.909183413065, -4.2728217370211, -4.6594352501557, -5.0596677431274, -0.47942529449565, -0.61046830506749, -0.81822139927716, -1.0713883147726, -1.3580707735185, -3.1940623983349, -3.4878681983455, -3.8349750153845, -4.2088588836045, -4.5996053556774, -0.035621955913741, -1.0228233420905, -1.9850469054155, -2.8987946978859, -3.7417525724225, -0.63334419275989, -1.781366010922, -2.8858860406286, -3.9199313878296, -4.8582501830767, -0.53084556684767, -1.2110575853691, -3.3304556093096, -4.4025504016937),ncol=1)

 solve(A, b)``

**Comment by markrogoyski** [comment] 2020-09-28 17:56
I used the internal `rref` to solve it instead of the LU decomposition and got the same answer as R. Getting the correct answer is more important than speed. I might just fallback and use the RREF for now and investigate what to do with LU when there are numerous zeros and NANs in there.

**Comment by markrogoyski** [comment] 2020-09-28 18:13
Actually, I'm not sure if that should have even worked, because this matrix is singular. The singular check using the determinant is not taking into account the floating point error. Fixing that would have identified this as singular and not proceeded to attempt to find the inverse.

**Comment by markrogoyski** [comment] 2020-09-28 18:20
Without completely rewriting everything, I think a simple fix for now is to check if the matrix is singular, and if so, just do a standard RREF solve of the system.

Something like this will get the right answer here:
```php
        $Ab = $this->augment($b->asColumnMatrix());
        $rref = $Ab->rref();
        return new Vector(array_column($rref->getMatrix(), $rref->getN() - 1));
```

**Comment by Beakerboy** [comment] 2020-09-28 18:57
My limited research shows that sparse matrices are typically solved iteratively instead of decomposing them to save on memory, but this does not appear to be a memory issue.

QR decomposition should work here too. Since Q is orthogonal, its inverse is its transpose. and R is upper diagonal:
```php
$decomp = $A->qrDecomposition();
$Q = $decomp['Q'];
$R = $decomp['R'];
$x = $R->solve($Q->transpose()->multiply($b));
```

**Comment by Labaneseren** [comment] 2020-09-28 19:21
This works! The `rref` does the trick nicely! 
However, this will only work if the left part of the Ab matrix (the first 49 columns in this case) can be reduced to an identity matrix. This is not always the case. But it my case it will always be, so I am content :) 
Also, I don't believe this matrix is singular. It's determinant is 1.0017879417442E-19, but not zero. 
Thanks again! 
The QR decomposition didn't work for me.

**Comment by markrogoyski** [comment] 2020-09-28 19:30
@Labaneseren,

We will fix it so the `solve` method does the right thing and you don't have to manually manipulate different decompositions of the Matrix. `solve` should do the right thing and you as the user should not know the details of what is going on as long as it produces the right result.

@Beakerboy,

Thanks for reminding me about QR. That is another option. I'll do some more investigation and come up with a procedure for determining what algorithm to use to solve the linear system in the `solve` method.

**Comment by Beakerboy** [comment] 2020-09-28 19:43
Is the determinant REALLY 1E-19, or is that due to floating point errors? MathPHP has a rational number object that can be used in a matrix. You could make a matrix where each element is a Rational object with the correct numerator and denominator, and calculate its determinant. The answer will be a Rational number and all the math will be performed with integer arithmatic.

**Comment by markrogoyski** [comment] 2020-09-28 19:48
For reference, R has a similar determinant calculation, but it also identifies the matrix as singular.
```R
> det(M)
[1] 1.001788e-19
> 
> is.singular.matrix(M)
[1] TRUE
```
I imagine they do something like we do and have an error tolerance. Also, the Matrix class allows you to define what you want the error tolerance to be incase you want 1.0e-19 to not be considered as 0.

**Comment by Beakerboy** [comment] 2020-09-28 20:07
Excel calculates a small determinant too. It appears that all the matrix elements are rational numbers, with 322560 in the denominator. Scaling it by that value, and calculating the determinant of the integer matrix, gives a very large number.

**Comment by markrogoyski** [comment] 2020-10-06 05:29
I've made some changes for the next release. Previously the `Matrix->solve($b)` method would try some basic strategies, and then default to LU decomposition if none of them worked. However, there are issues with singular matrices and division by zero with the LU decomposition for some matrices, and that is what @Labaneseren was experiencing.

For now, to "fix" this, if LU decomposition solve fails, it will try QR decomposition, and if that fails, then it will resort to augmenting the matrix and solving the RREF.

There is probably a more stable way to do this, or at least do some checks to figure out what method will work before trying and moving on to the next, and I will investigate it further. But for now, the improved behavior is more likely to solve the system of linear equations without producing an error than before.

Also, I've added functionality to solve directly from an LU decomposition and an QR decomposition. Both of those objects now have a `solve($b)` method. Further, I've added an optional `method` parameter to the `Matrix->solve($b)` function to force it to use a specific method (LU, or inverse, or QR, or RREF, for instance).

I've also added a lot more unit test cases for solve.

The current algorithm to solve the matrix isn't perfect, but it is better than it was. Hopefully there will be fewer issues. I will do more research to make it more stable.

In coming up with this fix, I discovered that different libraries produce different results for the LU decomposition. Some just error out and don't attempt to proceed if the matrix is singular, or if there are some divisions by zeros. However, SciPy and R (sometimes) will still produce a result with numbers in all locations. Other online calculators will produce NANs in those locations, which is what MathPHP currently does. SciPy seems to use a different pivoting strategy as well. I may need to investigate what SciPy is doing to come up with a result in these cases, and whether or not it even makes sense to produce a result, especially if the result doesn't equate back to the original matrix.

BTW, @Beakerboy, the way I am solving the linear equations with QR is by solving x = R⁻¹Qᵀb.
In code it would look something like this:
```php
$QR = $A->qrDecomposition();

$Qᵀ  = $QR->Q->transpose();
$Qᵀb = $Qᵀ->multiply($b);

$R⁻¹ = $QR->R->inverse();
$x   = $R⁻¹->multiply($Qᵀb);
```

The new `QR->solve($b)` basically does the same thing.

@Labaneseren,
Thank you for reporting this issue. We will continue to make improvements going forward to make sure the Matrix does the right thing.

**Comment by markrogoyski** [comment] 2020-10-13 06:13
This bug has been addressed in the latest release, v1.5.0. The Matrix in question will solve for Ax = b and get the expected result. The Matrix solve is a little smarter.

I think there is still a lot of room for improvement and plan to continue making it more robust, but for now I'm going to call this fixed.

Thank you again for reporting this issue and your interest in MathPHP.

**Closed by markrogoyski** 2020-10-13 06:13 UTC
Labels: bug

**Comment by Labaneseren** [comment] 2020-10-17 18:30
Hi Mark 
Did you check out the time it takes to solve the matrix with your new matrix->solve, vs. the rref? 
I get response times of around 8 sec. versus less than 1 sec using the rref directly. 
I assume it is the solve method trying to solve it by other decomposition means before resorting to rref? 
Or, it might be my local server (xampp).

**Comment by markrogoyski** [comment] 2020-10-18 06:09
Hi @Labaneseren,

There are two regression unit tests for this matrix in the test suite: one for RREF solve directly, and one using the Matrix::solve method., so you can test each one individually.

On my older 2014 2.8 GHz Intel Core i5 Macbook Pro, the RREF solve unit test takes around 75 ms, whereas the Matrix solve takes around 650 ms. So the Matrix solve is significantly slower, due to trying and failing with a couple of more numerically stable and preferable strategies, but it shouldn't be taking 8 seconds unless you are doing this on really old hardware or resource-limited VM or something.

Anyways, my goal for this bug report was to first make it work correctly. Slow code that gets the correct answer is better than code that gets the wrong answer really fast. Also, there were many new unit tests added, as well as unit tests specifically for the Matrix in this bug report. Therefore, we can take further steps to optimize and make it faster without worrying about breaking the current working functionality.

One optimization I am considering is for the Matrix solve to ask the Matrix some questions to be smarter about what solve strategy it uses. If the matrix is singular, for instance, it probably doesn't need to try doing an LU or possibly QR solve first. Doing that, then the Matrix solve only took around 85 ms because it computed the determinant and skipped straight to the RREF solve.

I will continue to investigate and experiment with optimizations to make it faster. But it was more important to correct the error and get a fix out than to optimize speed in the short term.

**Comment by Labaneseren** [comment] 2020-10-18 07:10
Hi Mark 
I understand, and I think it's a good approach. 
It's probably my apache emulator clogging up somewhere. 
Keep up the good work. Really appreciate it ;)
