### ISSUE TITLE
Discussion - Refactor Distributions

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#10] opened 2016-07-21 16:01 UTC
What do you think? Have you looked at my code? Each distribution has a PDF, and CDF function. The parent Distribution class has an inverse method which uses Newton's method to do the inverse CDF. For Student-T, I have a separate "two-tails" method which uses the same process to get the tails.

In reality, this is all well-and-good for continuous distributions. I need to rename my Distribution class to Contunuous and create a Discrete class which will operate in discrete terms.

Additional distribution statistics could be added to each child type without cluttering up one big class, each could have it's own mean, mode, skew, etc.

**Comment by Beakerboy** [comment] 2016-07-21 16:39
Exception Handling:
Is there an elegant way to define the acceptable types and ranges of the inputs to a distribution, so the parent can do error checks when constructing the object? Should each child have a method Linear::checkData(), or should there be some sort of meta-data array in each distributions class, which defines each parameter's data type, range, and the like? I'm thinking like a schema definition:

    $distribution_schema[
      $mu => [
        'type' => 'float',
        'l_bound' => '-INF',
        'u_bound' => 'INF';
      ],
      $sigma_squared => [
        'type => 'float',
        'l_bound' => 0,
        'u_bound => 'INF',
      ],
    ];

That might be unnecessarily complex, but it would be easy to read and edit, and allow the parent to do the error checking.

**Comment by markrogoyski** [comment] 2016-07-21 17:26
I like that idea. Instead of every constructor doing a custom check of each variable, have a generic way to specify and call a common function. I'll give some thought to this and see what I can come up with. The type wouldn't be necessary as PHP7 can check the type of int/float in the parameter list as a type hint.

**Comment by Beakerboy** [comment] 2016-07-21 19:54
I've just created a pull request to refactor the Distributions. It's a reorganization more than a feature addition. There are a few new distributions, like Student's-T, F, and Chi-Squared.

**Comment by Beakerboy** [comment] 2016-08-05 13:54
Have you thought about error checking the bounds?

I just added getMeans() to all the distributions. There are situations where some of these distributions do not have a mean. would you prefer the function return NULL, or some other "value".

Some of the distributions have the PDF and CDF defined as ($x, ...$params) and some as (...$params, $x) do you have a preference?

**Comment by markrogoyski** [comment] 2016-08-05 16:54
Thanks for adding means. This was on my to-do list. I was also thinking about adding median, variance, skewness, etc. What do you think?

When a distribution has a mean that is undefined, I think returning null seems the most appropriate.

A quick note on naming conventions. The general scheme I was using was if there was a calculation involved, to just use the mathematical term. So most functions are just the function or mathematical noun, like mean, evaluate, skewness, PDF, etc. So I'd go with just mean for the distribution means.
I was only using getSomething for getting class attributes. For example, the Matrix class has getRow, getMatrix etc. to get the class attributes; but everything else is just the term: add, trace, transpose, norm, etc.

For the parameters, I was looking at R and it seems like they usually put the $x type variable first, and then the other parameters (shape, mean, sd, lambda, etc.). That seems like a reasonable model to follow.

Regarding the interface, since the distributions are all static functions, you don't really gain much by having an interface. If we changed to instantiating classes, then it would make more sense.
For example, with the Regressions, since they are instantiable objects, you could pass your Regression to another function or class that could use it to predict values for whatever it does. Instead of accepting a specific type of Regression, it could accept a Regression interface (or parent class), and any subclass (or class that implements the interface) that gets passed to it, you know that you will always have an evaluate() function to predict values.

It really depends on the use case. Probability distribution PDFs and CDFs seem more like straight mathematical functions that have input and output, similar to built in functions like log() or exp() etc. You wouldn't create a class for those and pass those into a function--you'd just use them as is knowing that they work and always return the same output for a certain input. A Regression for on the other hand for example, all of the methods depend on the initial attributes provided in the constructor (the points). Since the distributions don't have any class attributes, it doesn't seem to warrant making it an instantiable class that would need an interface.

Does that make sense?

**Comment by Beakerboy** [comment] 2016-08-05 16:58
Sounds good. The reason I was asking, is I was going to set the Continuous::inverse() function to use the mean or mode if mean is undefined as the initial value to find the inverse. I did have it set to .5, but when testing the ChiSquared distribution with degrees or freedom=10, the newton's method was crapping out. Starting in the middle of the CDF will make more sense (I think).

I'll just have to do a test to see if self::mean() exists before calling it.

**Comment by markrogoyski** [comment] 2016-08-05 17:06
In that case, it probably makes sense to add an abstract mean method to the parent Continuous class, and each class will implement its own mean. So the check would be to verify that the return value from mean isn't null.

**Comment by markrogoyski** [comment] 2016-08-05 17:08
Actually, that won't work because the mean function signatures will differ.

**Comment by Beakerboy** [comment] 2016-08-05 17:09
Can you use the splat operator in the parent, and use a list in the children?

**Comment by markrogoyski** [comment] 2016-08-05 17:27
That will be an error. Something like this:
PHP Fatal error:  Declaration of C::test($a, $b) must be compatible with P::test(...$params)

**Comment by Beakerboy** [comment] 2016-08-06 12:27
Look at this for bounds setting, and let me know what you think:
https://github.com/Beakerboy/math-php/tree/parameter-checks

**Comment by markrogoyski** [comment] 2016-08-07 01:08
Cool. I like the idea. It will definitely make unit testing easier since testing each method's bounds error won't be needed anymore.

I have three suggestions to improve it.

1) Make the limits array an associative array with the parameter as the key.
For example:
```
    protected static $distribution_limits = [
       // x ∈ (0,1)
        x => [ 
            'lower_endpoint' => '[',
            'lower_value' => 0,
            'upper_endpoint' => ']',
            'upper_value' => 1,
        ],
        // α > 0
        α => [
            'lower_endpoint' => '(',
            'lower_value' => 0,
            'upper_endpoint' => ')',
            'upper_value' => INF,
        ],
         // β > 0
        β => [
            'lower_endpoint' => '(',
            'lower_value' => 0,
            'upper_endpoint' => ')',
            'upper_value' => INF,
        ],
    ]; 
```
Right now it is an ordered array, and this requires the calling function to order the parameters in the correct order or else it won't match the limits array. So now, the caller will send an associate array as well, keyed by the parameter names:
`self::checkLimits([ 'x' => $x, 'α' => $α, β => $β]);`

And the check function would just accept a single associate array as a parameter.
`public static function checkLimits(array $params)`

This way, there is no room for human error to mess up the order of the parameters.

2) Make checkLimits also accept the $limits array, so it takes two parameters:
`static function checkLimits(array $limits, array $params)`
This will make unit testing a lot easier and make it more clear where the limits come from than using the late static binding magic.

3) Make the limits array a class constant.
`const DISTRIBUTION_LIMITS = [ ...`

We don't want anyone to change the limits. And, as a public constant, the calling code can 'query' the class to find out what the bounds limits are if necessary without being able to modify them.

4) Now, if you want to get crazy with it, I have another idea:
Instead of an array like this:
```
        x => [ // x ∈ (0,1)
            'parameter' => 'x',
            'lower_endpoint' => '[',
            'lower_value' => 0,
            'upper_endpoint' => ']',
            'upper_value' => 1,
        ],
```
How about using the ISO 31-11 string notation. For example:
```
   const LIMITS = [
       'x' => '[0,1]',
       'α' => '(0, ∞)',
       'β' => '(0, ∞)',
    ];  
```
Then, in the checkLimits method, it could wrap the case statements in a regular expression match that would capture the endpoint character and values, and then proceed with the check.
```
if (preg_match('/^ ([[(]) (.+) , (.+?) ([])]) $/x'), $limit, $matches ) {
   ...
}
```
Now, we'd need some logic to convert any special characters like ∞ to INF if they are present. It would certainly make the parameter limits clear and concise and self documenting.

Thoughts?

**Comment by Beakerboy** [comment] 2016-08-07 01:51
Good plan.
However, as much as I like using regex, I'd probably just pop the first and last characters off, then split the remainder at the comma. Regular expressions can seem like black magic, or 'danger, here there be dragons'.

Can a class constant be an array in new PHP versions? I'll have to look that up. If not, I can make each limit a constant, and then make an array from them.

**Comment by Beakerboy** [comment] 2016-08-07 14:26
All suggestions implemented...even the crazy one :-)

Pull request sent.

**Comment by markrogoyski** [comment] 2016-08-07 20:27
I've merged it. I think I'll move it to a base class 'Distribution' that both Continuous and Discrete can inherit from since this is useful beyond just Continuous distributions.

**Closed** 2016-08-08 01:57 UTC

**Comment by markrogoyski** [comment] 2016-08-09 01:56
Please see: https://github.com/markrogoyski/math-php/issues/55
