### ISSUE TITLE
Bug for the t-test?

### ISSUE THREAD

**Issue by leonardo-boulay** [markrogoyski/math-php#458] opened 2022-11-23 18:36 UTC
Let's take these values:

$values = array();
for ($i=0; $i < 95; $i++) {$values[] = 1;}
for ($i=0; $i < 5; $i++) {$values[] = 0.5;}
for ($i=0; $i < 12; $i++) {$values[] = 0;}

$arraytTest = Significance::tTest($values, 0.569);

this leads to:

Warning: Division by zero in C:\xampp\htdocs\chess-boulayo\vendor\markrogoyski\math-php\src\Functions\Special.php on line 1121

Warning: Division by zero in C:\xampp\htdocs\chess-boulayo\vendor\markrogoyski\math-php\src\Functions\Special.php on line 1121

Warning: Division by zero in C:\xampp\htdocs\chess-boulayo\vendor\markrogoyski\math-php\src\Functions\Special.php on line 1121

if I do the same with tTestOneSampleFromSummaryData, but rounding numbers, it works.

**Comment by markrogoyski** [comment] 2022-11-24 05:36
Hi @leonardo-boulay,

Thank you for your interest in MathPHP, and thank you for reporting this issue.

I was able to reproduce the issue using your input. It looks like the issue is deep down the stack in the `regularizedIncompleteBeta`, and specifically in the helper `iBetaCF` regularized incomplete beta function. I'll take a look and see if I can determine the cause.

Thanks again for reporting this issue.
Mark

**Comment by leonardo-boulay** [comment] 2022-11-24 08:59
Thank you for your work!

**Comment by leonardo-boulay** [comment] 2022-11-24 09:51
(If you need another example, I found it)

$values = array();
for ($i=0; $i < 107; $i++) {$values[] = 1;}
for ($i=0; $i < 7; $i++) {$values[] = 0.5;}

$arraytTest = Significance::tTest($values, 0.85);

**Comment by leonardo-boulay** [comment] 2022-11-24 16:56
I temporary solved in this (horrible) way (but it works)


    private static function iBetaCF(int $m, float $x, float $a, float $b): float
    {
        $limits = [
        'x'  => '[0, 1]',
        'a'  => '(1,∞)',
        'b'  => '(1,∞)',
        ];
        $fraction_array = [];
$divisionbyzero = 1;
$counter = 0;
while ($divisionbyzero ==1 && $counter<50){
	$counter++;
        Support::checkLimits($limits, ['x' => $x, 'a' => $a, 'b' => $b]);

        $beta     = self::beta($a, $b);
        $constant = $x ** $a * (1 - $x) ** $b / $beta;
	
        $α_array = [];
        $β_array = [];
        for ($i = 0; $i < $m; $i++) {
            if ($i == 0) {
                $α = 1;
            } else {
                $α = ($a + $i - 1) * ($a + $b + $i - 1) * $i * ($b - $i) * $x ** 2 / ($a + 2 * $i - 1) ** 2;
            }
            $β₁        = $i + $i * ($b - $i) * $x / ($a + 2 * $i - 1);
            $β₂        = ($a + $i) * ($a - ($a + $b) * $x + 1 + $i * (2 - $x)) / ($a + 2 * $i + 1);
            $β         = $β₁ + $β₂;
            $α_array[] = $α;
            $β_array[] = $β;
        }

$divisionbyzerothistime= 0;

        $fraction_array = [];
        for ($i = $m - 1; $i >= 0; $i--) {
            if ($i == $m - 1) {
                $fraction_array[$i] = $α_array[$i] / $β_array[$i];
            } else {
            	if (abs(($β_array[$i] + $fraction_array[$i + 1]))<1.0E-40){$divisionbyzerothistime= 1; break;}
                $fraction_array[$i] = $α_array[$i] / ($β_array[$i] + $fraction_array[$i + 1]);
            }
        }
		
if ($divisionbyzerothistime==1){$divisionbyzero = 1; $x=$x+0.00000000001;}
else{$divisionbyzero = 0;}

}
        return $constant * $fraction_array[0];
    }

**Comment by robsheldon** [comment] 2022-12-27 06:06
Hi @leonardo-boulay, I think I have a pull request that resolves this for you. Can you double-check? I don't have a good way to verify the values produced by `Significance::tTest()`, but I think the underlying functions are producing the right outputs.

**Comment by markrogoyski** [comment] 2022-12-31 07:20
This has been fixed in the latest release [v2.7.0](https://github.com/markrogoyski/math-php/releases/tag/v2.7.0). Many thanks to @robsheldon for providing the fix.

**Closed by markrogoyski** 2022-12-31 07:20 UTC
